# numpy products

In [2]:
import numpy as np

### 1-D array in numpy

In [9]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
arr1 = np.array(42)
print(arr1)

42


### 2-D array

In [26]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


### 3-D array

In [30]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### checking dimensions

In [36]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
0
2
3


## indexing
### add an elements from diff arrays

In [53]:
a = arr[1]+arr2[1,2]
print(a)

8


In [57]:
a = arr3[1,0,2]
b = arr3[0,0,2]
print("{} and {}".format(a,b).split(" "))


['3', 'and', '3']


### printing last two numbers using
# Slicing

In [65]:
arr4 = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [6, 7, 8, 9, 10]])
print(arr4[0::, -2:])

[[ 4  5]
 [14 15]
 [ 9 10]]
